# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ionosctl < Formula
  desc "IonosCTL is a tool to help you manage your Ionos Cloud resources directly from your terminal."
  homepage "https://github.com/ionos-cloud/ionosctl"
  version "6.6.7"
  license "Apache-2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.6.7/ionosctl-6.6.7-darwin-arm64.tar.gz"
      sha256 "bebb04ad0d9b55dad370efa2cc05cd65d13a8898470078775aca33dc78534086"

      def install
        bin.install "ionosctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.6.7/ionosctl-6.6.7-darwin-amd64.tar.gz"
      sha256 "384f38de7065e36ff567beffb6bbb308eea20ac82366d0286ffcab39899ea807"

      def install
        bin.install "ionosctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.6.7/ionosctl-6.6.7-linux-amd64.tar.gz"
      sha256 "dda6e978e443da3414209653220d1f033561cc3b10a4bb7f40e8c8603a5e2c25"

      def install
        bin.install "ionosctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.6.7/ionosctl-6.6.7-linux-arm64.tar.gz"
      sha256 "77bda00dd297f292f0027f7956a30731e775daab545ebe9be59f787e3083ebe2"

      def install
        bin.install "ionosctl"
      end
    end
  end
end
