# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ionosctl < Formula
  desc "IonosCTL is a tool to help you manage your Ionos Cloud resources directly from your terminal."
  homepage "https://github.com/ionos-cloud/ionosctl"
  version "6.7.8"
  license "Apache-2.0"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.7.8/ionosctl-6.7.8-darwin-amd64.tar.gz"
      sha256 "bbce1a0ef25158918fa5d6538cd7b4ba50a4f997e00a7e3aa5af087ea4646d45"

      def install
        bin.install "ionosctl"
      end
    end
    on_arm do
      url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.7.8/ionosctl-6.7.8-darwin-arm64.tar.gz"
      sha256 "929ebbe075d3c8c49ce2985f1077eaa33bf09b64c511f41bad98e8f3f0c94726"

      def install
        bin.install "ionosctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.7.8/ionosctl-6.7.8-linux-amd64.tar.gz"
        sha256 "bc0621e42506b8367986bed97f4f6d19fcc9b5c35cfcdafdc9c1a86a1221a22a"

        def install
          bin.install "ionosctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ionos-cloud/ionosctl/releases/download/v6.7.8/ionosctl-6.7.8-linux-arm64.tar.gz"
        sha256 "66319492538d1f8c726ebcf7c78c35c241baa16e2f8905c8313f143813e27775"

        def install
          bin.install "ionosctl"
        end
      end
    end
  end
end
