# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IonoscloudMcp < Formula
  desc "MCP server bridging LLM clients to IONOS Cloud APIs."
  homepage "https://github.com/ionos-cloud/ionoscloud-mcp"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v0.1.2/ionoscloud-mcp-0.1.2-darwin-amd64.tar.gz"
      sha256 "64c3fafefee23a194caa46a1b1718b19b6d413923c869291638696711c1286f0"

      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v0.1.2/ionoscloud-mcp-0.1.2-darwin-arm64.tar.gz"
      sha256 "920460235b1e990ab2e097bb0c8a7afac0d3506e185bfef9252d233f57336de2"

      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v0.1.2/ionoscloud-mcp-0.1.2-linux-amd64.tar.gz"
      sha256 "1d1b69f1d0b9dbe354f2c331f9d963e9c7b6e032b71a4fcbb2c779fa276944e9"
      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v0.1.2/ionoscloud-mcp-0.1.2-linux-arm64.tar.gz"
      sha256 "bafd936c38282ddcd507d43cfb4187807701b8f59010bd3d066b740d88a8ac46"
      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
  end

  test do
    assert_match "ionos-cloud-mcp", shell_output("#{bin}/ionoscloud-mcp --version")
  end
end
