# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IonoscloudMcp < Formula
  desc "MCP server bridging LLM clients to IONOS Cloud APIs."
  homepage "https://github.com/ionos-cloud/ionoscloud-mcp"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v1.1.0/ionoscloud-mcp-1.1.0-darwin-amd64.tar.gz"
      sha256 "97ab51bfca398bb81e689c6c9ca5e0afdfa7827a48e1bd2535ad88e028f2f5d4"

      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v1.1.0/ionoscloud-mcp-1.1.0-darwin-arm64.tar.gz"
      sha256 "e6d038ed385eced4f70136c33940b10fd2d6d507f30c31d5b0128641ba076c40"

      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v1.1.0/ionoscloud-mcp-1.1.0-linux-amd64.tar.gz"
      sha256 "f77d3d6d80373b1bf641c20937116da22fbf3c07d16d1fe2e495d5d3a2670bfd"
      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ionos-cloud/ionoscloud-mcp/releases/download/v1.1.0/ionoscloud-mcp-1.1.0-linux-arm64.tar.gz"
      sha256 "f46ec1da24c1a7b1f93a417922a305d1591e0d7429d584cc782344ccc19b123f"
      define_method(:install) do
        bin.install "ionoscloud-mcp"
      end
    end
  end

  test do
    assert_match "ionos-cloud-mcp", shell_output("#{bin}/ionoscloud-mcp --version")
  end
end
